trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="$(System.DefaultWorkingDirectory)\\WebAppContent"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\\WebAppContent'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Publish the ZIP file as a pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the generated ZIP file
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy the published artifact to Azure Web App
- task: AzureWebApp@1
  inputs:
    appType: 'webApp'
    appName: 'maizeapi'
    package: '$(Build.ArtifactStagingDirectory)/*.zip'  # Artifact location
    deploymentMethod: 'auto'
    azureSubscription: 'Azure subscription 1(0d258a04-facb-4bd2-a95f-8797ca52d660)'
